# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 68940073+paulOgwulumba@users.noreply.github.com
author_name: Paul Ogwulumba
cloud_provider: none
preset_name: production
project_name: crowd_fund_typescript-frontend

